export const ENTER_TIME_IN_SECONDS = 0.25;
export const EXIT_TIME_IN_SECONDS = 0.25;

const ANIMATION_OFFSET = 0.5;

export const ENTER_ANIMATION_TIME = ENTER_TIME_IN_SECONDS + ANIMATION_OFFSET;
export const EXIT_ANIMATION_TIME = EXIT_TIME_IN_SECONDS + ANIMATION_OFFSET;
